"""
An event that occurs on the rod.

"""

from time import gmtime


class RodEvent:
    """

    Events are used to trigger spells.
    Spells will be triggered by a sequence of these events, typically generated by hardware.
    Examples of events are:

    * A button is pressed.
    * A gesture/stamp of the rod
    * A temperature change
    * A pressure change
    * Reaching a GPS location

    Events are immutable

    Hardware hints - Events can specify hardware they need to be generated using
    strings.

    """

    def __init__(self, name, created=gmtime(), event_type="none") -> None:
        self.name = name
        self.created = created
        self.event_type = event_type

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, RodEvent):
            return NotImplemented
        return self.__dict__ == other.__dict__

    def __hash__(self):
        return hash((self.name, self.created, self.event_type))

    def get_name(self) -> str:
        """get name"""
        return self.name

    def get_created(self) -> int:
        """get time/date event was created"""
        return self.created

    def get_event_type(self) -> str:
        """get event_type"""
        return self.event_type
